# Development Environment
app:
  build: .
  command: /opt/wildfly/bin/standalone.sh --debug 8787 -b 0.0.0.0 -bmanagement 0.0.0.0
  volumes:
    - ./headbanging-app/target/headbanging-app.war:/opt/wildfly/standalone/deployments/headbanging-app.war:ro
  ports:
    - "49990:9990"
    - "48080:8080"
    - "48787:8787"
  links:
    - localdb:localdb
localdb:
  build: database/
  #Will override values of Dockerfile
  environment:
    MYSQL_DATABASE: localdb
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: admin123
  ports:
    - "43306:3306"
