# Development Environment
app:
  build: .
  command: /opt/wildfly/bin/standalone.sh --debug 8787 -b 0.0.0.0 -bmanagement 0.0.0.0
  ports:
    - "49990:9990"
    - "48080:8080"
    - "48787:8787"
  links:
    - headbanging-db:headbanging-db
headbanging-db:
  build: database/
  #Will override values of Dockerfile
  environment:
    MYSQL_DATABASE: headbanging-db
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: admin123
  ports:
    - "43306:3306"
