# Development Environment
app:
  build: headbanging-app/
  command: java -jar payara-micro.jar --domainConfig headbanging-domain.xml
#  build: headbanging-app/
#  command: "/opt/payara41/glassfish/bin/asadmin start-domain payaradomain"
#  command: ls /opt/payara41/glassfish/domains/payaradomain/autodeploy/
  ports:
    - "49009:9009"
    - "48080:8080"
    - "44848:4848"
  volumes:
    - ./headbanging-app/target/:/opt/payara-micro-wars/
  links:
    - headbanging-db:headbanging-db
headbanging-db:
  build: database/
  #Will override values of Dockerfile
  environment:
    MYSQL_DATABASE: headbanging-db
    MYSQL_USER: mysql
    MYSQL_PASSWORD: mysql
    MYSQL_ROOT_PASSWORD: admin123
  ports:
    - "43306:3306"
